const DB_DEFAULT = [
  {
    "id": "gh_grilles_ref",
    "annees": "S1-S2-S3",
    "categorie": "Grilles & Horaires",
    "sujet": "Grille horaire de référence WBE",
    "statut": "Accord / Projet",
    "actuelle": "Le volume total au Tronc Commun est de 32 périodes hebdomadaires de 50 minutes.",
    "future": "<table class='grid-table'><thead><tr><th>Discipline</th><th>S1</th><th>S2</th><th>S3</th></tr></thead><tbody><tr style='background:#fffbeb'><td>EPC</td><td>1</td><td>1</td><td>1</td></tr><tr style='background:#fffbeb'><td>Religion / Morale</td><td>1</td><td>1</td><td>1</td></tr><tr style='background:#fffbeb'><td>Français</td><td>6</td><td>4</td><td>4</td></tr><tr style='background:#fffbeb'><td>Langues anciennes</td><td>-</td><td>2</td><td>1</td></tr><tr style='background:#fffbeb'><td>Langue moderne I*</td><td>4</td><td>4</td><td>4</td></tr><tr style='background:#fffbeb'><td>Mathématiques</td><td>5</td><td>5</td><td>4</td></tr><tr style='background:#fffbeb'><td>Sciences</td><td>3</td><td>3</td><td>3</td></tr><tr style='background:#fef3c7'><td><strong>FMTTN (Total)</strong></td><td>3</td><td>3</td><td>0</td></tr><tr class='sub-row'><td>↳ FMTT</td><td>1</td><td>1</td><td>0</td></tr><tr class='sub-row'><td>↳ Numérique</td><td>2</td><td>2</td><td>0</td></tr><tr style='background:#fffbeb'><td>FHGES</td><td>4</td><td>4</td><td>4</td></tr><tr style='background:#fffbeb'><td>Éd. culturelle et artistique</td><td>2</td><td>2</td><td>0</td></tr><tr style='background:#fffbeb'><td>Éd. physique et santé</td><td>3</td><td>3</td><td>2</td></tr><tr style='background:#fef3c7'><td>Module d'orientation</td><td>-</td><td>-</td><td>8</td></tr></tbody><tfoot><tr><td>Total disciplinaire</td><td>32</td><td>32</td><td>32</td></tr></tfoot></table><div class='grid-note'><strong>*LM2 :</strong> Retirée de la grille obligatoire. Subsiste comme module optionnel en S3.<br><strong>S1 :</strong> Le cours de langues anciennes est compris dans le cours de Français.<br><strong>S3 :</strong> Organisation de 8 périodes obligatoires de module d'orientation &amp; disparition du bloc FMTTN.</div>",
    "source": "APD S1 – Art. 1, 1° / Référentiels disciplinaires FWB",
    "alerte": "Mesure pérenne pour la grille horaire 32 x 50 minutes. Certaines modifications de blocs (FMTT, Numérique, FMTTN en S3) s'accompagnent de mesures transitoires pour le personnel précisées dans les fiches « Personnel & Fonctions ».",
    "visible": true
  },
  {
    "id": "lm1_choix",
    "annees": "S1",
    "categorie": "Grilles & Horaires",
    "sujet": "LM1 : choix de la langue à l’entrée en S1",
    "statut": "Accord / Projet",
    "actuelle": "En règle générale, l’élève poursuit en S1 la langue moderne suivie durant son parcours en enseignement primaire.",
    "future": "À partir de 2026-2027, les parents peuvent demander, lors de l’inscription en S1, que leur enfant suive une <strong>langue moderne I différente de celle apprise au primaire</strong>. Cette dérogation n’est possible que <strong>moyennant la décision favorable du directeur</strong>, prise au cas par cas dans le cadre fixé par le Code.",
    "source": "APD S1 – dispositions relatives au choix de la LM1 à l’entrée en S1",
    "alerte": "Vérifier systématiquement la langue suivie au primaire et documenter par écrit la décision du directeur (accord ou refus), compte tenu des contraintes d’organisation de l’établissement et du respect de l’ensemble des dispositions légales et réglementaires en vigueur.",
    "visible": true
  },
  {
    "id": "imm_bruxelles",
    "annees": "S1",
    "categorie": "Grilles & Horaires",
    "sujet": "Immersion linguistique à Bruxelles",
    "statut": "Accord / Projet",
    "actuelle": "Dans la Région de Bruxelles-Capitale, la Langue Moderne I est obligatoirement le néerlandais.",
    "future": "La double immersion (NL/EN) reste autorisée en S1 dans la Région de Bruxelles-Capitale. Règles strictes : le <strong>néerlandais reste la seule LM1 reconnue</strong> (4 périodes) ; <strong>aucun cours d’anglais autonome</strong> ne peut être organisé en S1 ; l’anglais s’enseigne <strong>uniquement via l’immersion</strong> dans d’autres disciplines conformément aux règles générales de l’immersion FWB.",
    "source": "APD S1 – dispositions relatives à la LM1 à Bruxelles / Règles immersion FWB / FAQ FWB – Tronc commun",
    "alerte": "Limiter cette règle au seul territoire de la Région de Bruxelles-Capitale. Toute heure d’anglais en S1 qui ne passe pas par un dispositif d’immersion (même présentée comme option ou module) est contraire au cadre légal. Toute organisation d’une double immersion NL/EN en S1 doit être vérifiée au regard des règles immersion FWB et anticipée dans la construction des grilles horaires.",
    "visible": true
  },
  {
    "id": "imm_double",
    "annees": "S1-S2-S3",
    "categorie": "Grilles & Horaires",
    "sujet": "Double immersion : plage horaire",
    "statut": "Accord / Projet",
    "actuelle": "La double immersion au Degré Inférieur devait couvrir au moins 8 et au plus 12 périodes par langue.",
    "future": "Le plancher est abaissé : dans le cadre d’une double immersion, la partie immersive doit couvrir <strong>au minimum 6 périodes et au maximum 13 périodes</strong> hebdomadaires par langue, offrant plus de souplesse sans imposer un second cours de langue moderne.",
    "source": "Code de l’enseignement – Art. 2.2.4-1, al. 2 (modifié par l’APD S1, art. 3)",
    "alerte": "Cette évolution (de 8 à 6 périodes) ne concerne que la double immersion. L’immersion simple conserve son plancher à 8 périodes hebdomadaires.",
    "visible": true
  },
  {
    "id": "fhges_orga",
    "annees": "S1-S2-S3",
    "categorie": "Grilles & Horaires",
    "sujet": "FHGES : Formation Historique, Géographique, Économique et Sociale",
    "statut": "Accord / Projet",
    "actuelle": "Les disciplines des sciences humaines sont organisées comme des cours séparés (Histoire, Géographie, Sciences économiques, Sciences sociales) avec des enseignants distincts.",
    "future": "Le FHGES constitue un bloc de <strong>4 périodes hebdomadaires</strong> regroupant Histoire, Géographie, Sciences économiques et Sciences sociales. Il peut être organisé soit en <strong>cours disciplinaires séparés</strong>, soit en <strong>bloc intégré confié à un seul enseignant</strong>, selon les choix du pouvoir organisateur, dans le respect du référentiel FHGES du tronc commun.",
    "source": "APD S1 – dispositions relatives au FHGES / Référentiel FHGES – enseignement.be / FAQ FWB – Tronc commun",
    "alerte": "Le choix entre organisation disciplinaire séparée et bloc intégré relève du pouvoir organisateur. En cas de bloc intégré, une concertation pédagogique renforcée est indispensable pour garantir la couverture de l’ensemble des attendus du référentiel FHGES et leur répartition sur les trois années, comme le rappellent les outils et FAQ FWB.",
    "visible": true
  },
  {
    "id": "eca_orga",
    "annees": "S1-S2",
    "categorie": "Grilles & Horaires",
    "sujet": "ECA : Éducation culturelle et artistique",
    "statut": "Accord / Projet",
    "actuelle": "L'organisation des cours artistiques est variable selon les écoles.",
    "future": "Le cours d’Éducation culturelle et artistique (ECA) est fixé à <strong>2 périodes hebdomadaires</strong> en S1 et en S2. Il intègre obligatoirement les trois langages : expression française et corporelle, expression plastique et expression musicale, travaillés chaque année, en lien avec le référentiel ECA du tronc commun.",
    "source": "APD S1 – Référentiel ECA / Référentiels du tronc commun – enseignement.be / FAQ FWB – ECA",
    "alerte": "La répartition entre les différents volets se fait en fonction des titres disponibles au sein de l’équipe. Il est possible de regrouper les périodes (par exemple 2 périodes d’ECA toutes les deux semaines, ou des blocs-projets) pour des raisons pédagogiques, pour autant que le volume annuel soit respecté et que les trois modes d’expression soient effectivement travaillés chaque année. La FAQ FWB recommande de planifier cette organisation au niveau de l’établissement et de la communiquer clairement aux parents.",
    "visible": true
  },
  {
    "id": "fmtt",
    "annees": "S1-S2",
    "categorie": "Grilles & Horaires",
    "sujet": "FMTT : Formation manuelle, technique et technologique",
    "statut": "Accord / Projet",
    "actuelle": "Le bloc FMTTN est un cours combiné de 3 périodes hebdomadaires.",
    "future": "Avec la scission du bloc FMTTN, la composante FMTT est organisée en <strong>1 période hebdomadaire</strong> en S1 et en S2. Les quatre champs (alimentation et habitat, techniques de culture, matières et matériaux, objets technologiques) restent d'application dans le référentiel.",
    "source": "APD S1 – Annexe FMTTN / circulaire FMTTN 2026-2027",
    "alerte": "Des mesures transitoires et des formations IFPC accompagnent la reconversion des enseignants de l’ancienne fonction de CT Éducation par la technologie DI vers la nouvelle fonction CT FMTT DI.",
    "visible": true
  },
  {
    "id": "numerique",
    "annees": "S1-S2",
    "categorie": "Grilles & Horaires",
    "sujet": "Formation au numérique : 2 périodes hebdomadaires",
    "statut": "Accord / Projet",
    "actuelle": "La formation numérique est intégrée au référentiel FMTTN sans allocation horaire distincte.",
    "future": "Le volet numérique est détaché en un cours spécifique de <strong>2 périodes hebdomadaires</strong> en S1 et en S2. Il reste aligné sur le référentiel FMTTN, avec une évolution annoncée vers <strong>DigComp 3.0</strong> (IA explicite/implicite, cybersécurité, lutte contre la désinformation, bien-être numérique) à partir de 2027-2028.",
    "source": "APD S1 – dispositions FMTTN / circulaire numérique (DigComp 3.0)",
    "alerte": "Un certificat de 12 ECTS en formation numérique sera organisé pour permettre la reconversion des enseignants vers la fonction de CT Numérique DI. Mesure transitoire à anticiper dans la gestion des ressources humaines.",
    "visible": true
  },
  {
    "id": "gh_derogation_sport",
    "annees": "S1-S2-S3",
    "categorie": "Grilles & Horaires",
    "sujet": "Dérogation : Sportifs et Espoirs de haut niveau",
    "statut": "Accord / Projet",
    "actuelle": "Des mécanismes généraux existent pour les sportifs de haut niveau, sans aménagement spécifique de la grille DI.",
    "future": "Pour les élèves reconnus sportifs de haut niveau, espoirs sportifs ou arbitres nationaux : possibilité de <strong>remplacer le cours d'EPS ainsi que 2 périodes au choix</strong> par un nombre équivalent de périodes d'entraînement sportif.",
    "source": "APD S1 – Art. 1, 6° (Ajout §4)",
    "alerte": "Cette dérogation nécessite l'accord explicite du directeur et doit être consignée formellement dans le dossier scolaire.",
    "visible": true
  },
  {
    "id": "gh_derogation_arts",
    "annees": "S1-S2-S3",
    "categorie": "Grilles & Horaires",
    "sujet": "Dérogation : Académies et Écoles supérieures des Arts",
    "statut": "Accord / Projet",
    "actuelle": "Aucune dérogation de ce type n'est prévue de manière explicite dans le Degré Inférieur actuel.",
    "future": "Pour les élèves inscrits dans une école supérieure des arts (Art. 107) : possibilité de <strong>remplacer le cours d'ECA ainsi que 2 périodes au choix</strong> par un nombre équivalent de périodes d'enseignement musical.",
    "source": "APD S1 – Art. 1, 7° (Ajout §5)",
    "alerte": "L'accord du directeur est requis et la décision doit figurer dans le dossier scolaire.",
    "visible": true
  },
  {
    "id": "gh_p45_p90",
    "annees": "S1-S2-S3",
    "categorie": "Grilles & Horaires",
    "sujet": "Flexibilité de la grille et P45/P90 (Art. 2.2.2-2)",
    "statut": "Accord / Projet",
    "actuelle": "L'horaire par défaut est de 32 périodes de 50 minutes (P50).",
    "future": "Afin d'intégrer l'Accompagnement Personnalisé (AP), le pouvoir organisateur peut, <strong>après avis de l'organe de concertation sociale</strong> (CoCoBa), s'écarter des 32x50 min pour choisir l'une des 3 grilles alternatives :<br><br><strong>1° Le P45/P90 :</strong> Grille de <strong>minimum 34 périodes de 45 minutes</strong>, regroupées autant que possible en plages de 90 minutes. Le temps dégagé finance structurellement 2 périodes d'AP.<br><strong>2° Demi-journées d'apprentissage concentré :</strong> Grille de 32 périodes (50 min) + organisation de <strong>18 demi-journées</strong> d'apprentissage concentré sur l'année.<br><s style='color:#a0aec0'><strong>3° Semaines d'apprentissage concentré :</strong> Option non retenue / non applicable.</s>",
    "source": "Code de l'Enseignement – Article 2.2.2-2, §1er / FAQ FWB – Tronc commun",
    "alerte": "Mesures pérennes quant aux modèles de grille. Quel que soit le modèle retenu (32x50, P45/P90, demi-journées concentrées), le plafond légal de 12 jours de suspension de cours au Degré Inférieur reste d'application. Les journées d’orientation AEO et autres journées concentrées doivent obligatoirement s’inscrire dans ce plafond et être planifiées dans le respect des nouveaux rythmes scolaires.",
    "visible": true
  },
  {
    "id": "ori_s3_module",
    "annees": "S3",
    "categorie": "Orientation",
    "sujet": "Module d'orientation S3 : 8 périodes hebdomadaires",
    "statut": "Accord / Projet",
    "actuelle": "En S3 actuel, il n'existe pas de module d'orientation spécifique dans la grille horaire.",
    "future": "En S3, <strong>8 périodes hebdomadaires</strong> sont consacrées au module d'orientation. Ce bloc remplace les cours FMTTN qui disparaissent en S3. Il est organisé autour de <strong>projets de découverte des filières</strong>, d'immersions en entreprises et d'ateliers d'orientation encadrés.",
    "source": "APD S1 – Grille de référence S3 / Décret du 16/05/2024",
    "alerte": "L'organisation du module d'orientation S3 nécessite des partenariats extérieurs (entreprises, CPMS, haute école). Une planification annuelle est indispensable.",
    "visible": true
  },
  {
    "id": "ap_global",
    "annees": "S1-S2-S3",
    "categorie": "Accompagnement (AP/AR)",
    "sujet": "Accompagnement personnalisé (AP) : principe général",
    "statut": "Accord / Projet",
    "actuelle": "Il n'existe pas de périodes structurelles dédiées à l'AP dans la grille actuelle du Degré Inférieur.",
    "future": "L'accompagnement personnalisé (AP) offre à chaque élève l'équivalent de <strong>2 périodes hebdomadaires</strong> de soutien ciblé au Degré Inférieur. Ces périodes sont <strong>intégrées dans le temps scolaire obligatoire</strong> et peuvent être organisées au sein de la grille standard ou des grilles alternatives (P45/P90).",
    "source": "Code – Art. 2.2.3-1 et 2.2.3-2 / APD S1 – Art. 10 et 11",
    "alerte": "Dispositif pérenne. Les périodes d'AP sont financées via un mécanisme spécifique (1 période-professeur par tranche entamée de 19 élèves de S1) et doivent être affectées exclusivement à l'accompagnement personnalisé.",
    "visible": true
  },
  {
    "id": "ap_contenu",
    "annees": "S1-S2-S3",
    "categorie": "Accompagnement (AP/AR)",
    "sujet": "AP : contenu et modalités d'organisation",
    "statut": "Accord / Projet",
    "actuelle": "Pas d'équivalent structurel dans l'organisation actuelle du 1er degré.",
    "future": "L'AP est <strong>centré sur les compétences de base</strong> (français, mathématiques, méthodes de travail) et sur le soutien à la motivation. Il peut être organisé en <strong>classe entière ou en sous-groupes</strong> flexibles. <strong>Le conseil de classe définit les priorités</strong> sur base des bilans DAccE. Il est <strong>interdit de constituer des groupes homogènes permanents</strong> et le titulaire ne peut pas avancer dans la matière avec les élèves restants lorsque certains sont extraits.",
    "source": "Code – Art. 2.2.3-1 et 2.2.3-2 / APD S1 / FAQ FWB – AP et accompagnement",
    "alerte": "Les modalités concrètes d'organisation de l'AP (plages horaires, critères de sélection, articulation avec le DAccE) doivent être communiquées clairement aux parents dès le début d'année scolaire, conformément aux recommandations de la FAQ FWB. Cette communication doit souligner le caractère de soutien et éviter toute représentation de filière parallèle ou de groupe de niveau permanent.",
    "visible": true
  },
  {
    "id": "ar_global",
    "annees": "S1",
    "categorie": "Accompagnement (AP/AR)",
    "sujet": "AR : Accompagnement Renforcé – Critères d'admission",
    "statut": "Accord / Projet",
    "actuelle": "Il n'existe pas de dispositif AR structurel dans la grille actuelle du 1er degré.",
    "future": "L'AR est destiné aux élèves admis en S1 sans CEB, ayant obtenu <strong>moins de 50%</strong> à une ou plusieurs parties du CEB, ou <strong>moins de 60% au total</strong>. Ces élèves sont <strong>répartis dans toutes les classes</strong> ordinaires. <strong>Interdiction formelle de former des classes homogènes</strong>.",
    "source": "APD S1 – Art. 6 et Art. 8 / FAQ FWB – AR et suppression de la 1re différenciée",
    "alerte": "L’AR remplace les anciennes structures de 1re différenciée : il s’agit d’un dispositif de soutien intégré au tronc commun, non d’une nouvelle filière. Les critères d’admission et l’organisation de l’AR doivent être expliqués aux parents dans un langage accessible pour éviter tout sentiment de stigmatisation, comme le rappelle la FAQ FWB.",
    "visible": true
  },
  {
    "id": "ar_financement",
    "annees": "S1",
    "categorie": "Accompagnement (AP/AR)",
    "sujet": "AR : Enveloppe de 10.000 périodes FWB",
    "statut": "Accord / Projet",
    "actuelle": "Non applicable dans la configuration actuelle.",
    "future": "Une <strong>enveloppe fermée de 10.000 périodes</strong> est réservée à l'échelle FWB pour financer l'AR. Calcul : <strong>0,5 période par élève</strong> inscrit au 15/01 concerné par un échec CEB. Une formule de lissage (N_final) s'applique si le total FWB diffère de l'enveloppe.",
    "source": "APD S1 – Art. 12 (Art. 16sexies/1bis) / FAQ FWB – AR et moyens d'encadrement",
    "alerte": "Mesure de financement à caractère transitoire : le calcul définitif est réalisé par l'Administration centrale. Ces moyens sont exclusivement réservés à la remédiation AR. La FAQ FWB insiste sur la nécessité d’affecter ces périodes à des dispositifs concrets (co‑enseignement, petits groupes, ateliers ciblés) et non à un simple renforcement général de la grille.",
    "visible": true
  },
  {
    "id": "dacce_global",
    "annees": "S1-S2-S3",
    "categorie": "Parcours & Évaluation",
    "sujet": "DAccE : Dossier d'accompagnement de l'élève",
    "statut": "Accord / Projet",
    "actuelle": "Un dossier scolaire existe mais sans structure normalisée pour l'accompagnement individualisé au Degré Inférieur.",
    "future": "Le DAccE devient le <strong>dossier numérique officiel</strong> qui suit l'élève tout au long du Tronc Commun, y compris en cas de changement d'établissement. Il rassemble les bilans de synthèse, les dispositifs d'accompagnement et les informations utiles à l'orientation. Certaines rubriques sensibles (échec CEB) ne sont <strong>consultables qu'en S1</strong> afin de garantir un <strong>droit à l'oubli</strong>.",
    "source": "Décret du 16/05/2024 – Livre 1, Titre 10 / APD S1 – Art. 21 à 24",
    "alerte": "La mise en œuvre du DAccE suppose une gestion rigoureuse des droits d'accès et une information claire des parents sur les données consultables.",
    "visible": true
  },
  {
    "id": "eval_examens",
    "annees": "S1",
    "categorie": "Parcours & Évaluation",
    "sujet": "Examens de passage : interdiction totale en S1",
    "statut": "Accord / Projet",
    "actuelle": "Les examens de passage sont tolérés dans certaines conditions strictes.",
    "future": "Dès la rentrée 2026, les examens de passage <strong>ne peuvent EN AUCUN CAS être organisés en S1</strong>. L'évaluation devient <strong>strictement continue et formative</strong>. Seule une <strong>décision de maintien exceptionnelle</strong> en fin d'année est possible. Il n'existe plus de seconde session en septembre.",
    "source": "APD S1 – Art. 13 (modifiant Art. 1.9.3-2, §1er)",
    "alerte": "Cette mesure implique une révision profonde des pratiques évaluatives en S1. La communication aux équipes doit être faite bien en amont de la rentrée.",
    "visible": true
  },
  {
    "id": "eval_dacce_oubli",
    "annees": "S1",
    "categorie": "Parcours & Évaluation",
    "sujet": "DAccE : Droit à l'oubli (Échec CEB)",
    "statut": "Accord / Projet",
    "actuelle": "Les données relatives à l'échec au CEB sont consultables par les équipes éducatives.",
    "future": "L'information sur l'échec CEB est inscrite dans le DAccE et <strong>consultable uniquement durant S1</strong>. Dès le passage en S2, cette trace <strong>disparaît automatiquement</strong> pour éviter tout effet d'étiquetage durable.",
    "source": "APD S1 – Art. 15 et Art. 24",
    "alerte": "Les équipes de S2 ne pourront plus consulter l'information sur l'échec CEB. La continuité du soutien repose sur les bilans de synthèse DAccE rédigés en S1.",
    "visible": true
  },
  {
    "id": "eval_bilan_s1",
    "annees": "S1",
    "categorie": "Parcours & Évaluation",
    "sujet": "Bilan de fin S1 : décision du conseil de classe",
    "statut": "Accord / Projet",
    "actuelle": "Le conseil de classe statue sur le passage ou le maintien en fin d'année selon les résultats obtenus.",
    "future": "En fin de S1, le conseil de classe peut prendre deux décisions : <strong>1° Passage en S2</strong> (décision ordinaire) ou <strong>2° Maintien exceptionnel en S1</strong>, soumis à une procédure formalisée et dûment motivée. <strong>Aucun examen de passage ni orientation vers une 2e différenciée n'est autorisé</strong> dans le cadre du Degré Inférieur.",
    "source": "APD S1 – Art. 13 à 15 / Dispositions relatives au Degré Inférieur",
    "alerte": "La suppression des examens de passage implique que toutes les décisions reposent sur l'évaluation continue et les bilans DAccE. Le maintien doit rester exceptionnel et documenté dans le DAccE.",
    "visible": true
  },
  {
    "id": "aeo_global",
    "annees": "S1-S2-S3",
    "categorie": "Orientation",
    "sujet": "Approche éducative de l’orientation (AEO) – 128 périodes",
    "statut": "Accord / Projet",
    "actuelle": "Au niveau primaire, l’orientation s’intègre de manière transversale dans les apprentissages sans périodes spécifiquement dédiées.",
    "future": "Au Degré Inférieur, l’AEO représente <strong>128 périodes sur l’ensemble du Tronc Commun</strong> : <strong>48 périodes intégrées aux cours</strong> (activités menées au sein des disciplines) et <strong>80 périodes hors cours</strong> (visites d’entreprises, salons, journées de découverte, rencontres de métiers). Ce dispositif <strong>ne modifie pas la grille horaire de 32 périodes de cours</strong> et s’inscrit dans les domaines transversaux, en particulier le domaine « Apprendre à s’orienter ». Il doit être articulé avec les référentiels du tronc commun et le projet d’établissement.",
    "source": "Décret du 16/05/2024 – Approche éducative de l’orientation / APD S1 / Référentiels du tronc commun – enseignement.be / FAQ FWB – AEO",
    "alerte": "La planification des 80 périodes hors cours, dont les deux journées de découverte (16 périodes), doit être anticipée dès le début d’année scolaire pour éviter les conflits avec les jours de cours ordinaires. L’AEO doit être inscrite explicitement dans le projet d’établissement et coconstruite avec le Centre PMS et les partenaires extérieurs (entreprises, opérateurs d’orientation…), comme recommandé dans la FAQ FWB.",
    "visible": true
  },
  {
    "id": "ori_journees",
    "annees": "S1-S2-S3",
    "categorie": "Orientation",
    "sujet": "Journées de découverte – 16 périodes obligatoires",
    "statut": "Accord / Projet",
    "actuelle": "Les sorties à visée orientante ne sont pas codifiées formellement dans la grille.",
    "future": "Deux journées d'activités orientantes sont <strong>obligatoires</strong>, représentant <strong>16 périodes prélevées sur les 80 périodes hors cours</strong> du dispositif AEO. Elles s'organisent durant les <strong>jours de suspension des cours autorisés</strong>.",
    "source": "APD S1 – Art. 1, 3° et Art. 35",
    "alerte": "La planification de ces deux journées doit figurer dans l'agenda scolaire dès la rentrée. Elles ne peuvent se tenir sur des jours de cours ordinaires.",
    "visible": true
  },
  {
    "id": "ori_carnet",
    "annees": "S1-S2-S3",
    "categorie": "Orientation",
    "sujet": "Carnet d'orientation",
    "statut": "Accord / Projet",
    "actuelle": "L'utilisation d'un carnet d'orientation est optionnelle et non structurée selon les établissements.",
    "future": "Un <strong>carnet d'orientation est remis gratuitement à chaque élève</strong> dès le début de S1. Il suit l'élève tout au long du Degré Inférieur, même en cas de changement d'établissement. Le carnet <strong>n'a aucun impact sur la cotation</strong>.",
    "source": "APD S1 – Art. 34",
    "alerte": "Chaque école élabore son canevas sur la base d'un modèle gouvernemental. La cohérence entre établissements doit être assurée.",
    "visible": true
  },
  {
    "id": "str_1diff",
    "annees": "S1",
    "categorie": "Structures & Inscriptions",
    "sujet": "Suppression de la 1re différenciée",
    "statut": "Accord / Projet",
    "actuelle": "La 1re année différenciée constitue une filière distincte pour les élèves sans CEB.",
    "future": "La 1re année différenciée <strong>disparaît totalement dès la rentrée 2026-2027</strong>. Tous les élèves entrent dans la <strong>1re année du Tronc Commun</strong> du Degré Inférieur. La 2e année différenciée subsiste de manière <strong>strictement transitoire en 2026-2027</strong> avant sa suppression définitive.",
    "source": "APD S1 – Art. 35 à 43 / Décret du 30/06/2006 modifié",
    "alerte": "Les moyens de l'ex-1re différenciée sont redistribués sous forme de périodes d'Accompagnement Renforcé (AR). Aucune nouvelle cohorte de 1re ou 2e différenciée ne sera organisée après la phase transitoire.",
    "visible": true
  },
  {
    "id": "str_2diff_transitoire",
    "annees": "S2",
    "categorie": "Structures & Inscriptions",
    "sujet": "2e année différenciée : maintien transitoire 2026-2027",
    "statut": "Accord / Projet",
    "actuelle": "La 2e année différenciée constitue une filière spécifique pour les élèves sans CEB.",
    "future": "La 2e année différenciée est <strong>maintenue à titre transitoire pour l'année scolaire 2026-2027</strong> uniquement, pour les élèves déjà engagés dans le dispositif. À partir de 2027-2028, elle disparaît au profit du Degré Inférieur organisé en Tronc Commun.",
    "source": "APD S1 – Art. 35 à 43 / Décret du 30/06/2006 modifié",
    "alerte": "Les élèves de 2e différenciée restent soumis à l'épreuve externe commune CEB. Aucune nouvelle admission en 2e différenciée ne sera possible après la phase transitoire.",
    "visible": true
  },
  {
    "id": "str_maintien_prim",
    "annees": "S1",
    "categorie": "Structures & Inscriptions",
    "sujet": "Élèves maintenus en primaire : gestion des inscriptions S1",
    "statut": "Accord / Projet",
    "actuelle": "Les demandes d'inscription en S1 des élèves maintenus restent actives dans les listes d'attente (CoGI), générant une gestion complexe.",
    "future": "Sauf demande contraire des parents, les <strong>demandes d'inscription S1 seront automatiquement supprimées</strong> dès que le refus du CEB est définitif. Les <strong>listes FUI seront purgées automatiquement</strong> fin juin.",
    "source": "APD S1 – Art. 30 (Art. 1.7.7-29, §2)",
    "alerte": "Les directions doivent informer les parents de cette règle lors des inscriptions pour éviter toute confusion.",
    "visible": true
  },
  {
    "id": "str_maintien_s1",
    "annees": "S1",
    "categorie": "Structures & Inscriptions",
    "sujet": "Maintien en S1 : procédure exceptionnelle",
    "statut": "Accord / Projet",
    "actuelle": "Le maintien en 1re année est possible après délibération du conseil de classe.",
    "future": "Le maintien en S1 est possible mais devient <strong>exceptionnel et soumis à une procédure formalisée</strong> : avis motivé du conseil de classe, consultation obligatoire des parents, rapport transmis au Centre PMS. <strong>Maximum 1 maintien sur l'ensemble du Degré Inférieur</strong>.",
    "source": "APD S1 – Art. 13",
    "alerte": "La procédure de maintien doit être documentée et transmise dans le DAccE. Le Centre PMS doit être impliqué dès le signalement.",
    "visible": true
  },
  {
    "id": "pers_ct_numerique",
    "annees": "S1-S2",
    "categorie": "Personnel & Fonctions",
    "sujet": "Fonction de CT Numérique DI – Dispositif transitoire",
    "statut": "Accord / Projet",
    "actuelle": "La formation numérique est assurée via le bloc FMTTN, principalement par des enseignants d'informatique ou de technologie sans fonction spécifique de CT Numérique DI.",
    "future": "La création d'une fonction de <strong>CT Numérique DI</strong> accompagne la mise en place des 2 périodes de numérique en S1-S2. Un <strong>dispositif transitoire</strong> permet la reconversion des enseignants en perte de charge (informatique / technologie), notamment via un <strong>certificat de 12 ECTS</strong> en formation numérique.",
    "source": "APD S1 – dispositions FMTTN / Titre II dispositions transitoires personnel / FAQ FWB – Tronc commun",
    "alerte": "Les directions doivent identifier les membres du personnel potentiellement concernés et planifier avec le PO leur accès au certificat 12 ECTS et aux nouvelles fonctions de CT Numérique DI.",
    "visible": true
  },
  {
    "id": "pers_ct_fmtt",
    "annees": "S1-S2-S3",
    "categorie": "Personnel & Fonctions",
    "sujet": "Fonction de CT FMTT DI – Dispositions transitoires",
    "statut": "Accord / Projet",
    "actuelle": "Les cours techniques et technologiques du 1er degré sont assurés par des fonctions de CT Éducation par la technologie, sans distinction FMTT.",
    "future": "La mise en place du bloc FMTT (1 période en S1-S2) et la disparition des cours FMTTN en S3 s'accompagnent de la création de la fonction de <strong>CT FMTT DI</strong>. Des <strong>mesures transitoires</strong> encadrent la reconversion et la réaffectation des professeurs d'ancienne fonction, avec maintien possible via des formations obligatoires à l'horizon 2029-2030.",
    "source": "APD S1 – Titre II, dispositions transitoires CT FMTT / Décret titres et fonctions / FAQ FWB – Tronc commun",
    "alerte": "Les directions doivent anticiper les pertes partielles de charge, informer les membres du personnel des formations obligatoires et vérifier les délais de candidature pour les nouvelles fonctions.",
    "visible": true
  },
  {
    "id": "eca_personnel",
    "annees": "S1-S2",
    "categorie": "Personnel & Fonctions",
    "sujet": "ECA : organisation des titres et partage du cours",
    "statut": "Accord / Projet",
    "actuelle": "Les cours artistiques sont organisés selon des schémas variables (un ou plusieurs enseignants) sans cadre commun lié au référentiel ECA.",
    "future": "Le cours d'Éducation culturelle et artistique (ECA) peut être <strong>assuré par un ou plusieurs enseignants</strong> en fonction de leurs titres, afin de couvrir les trois langages (expression française et corporelle, expression plastique, expression musicale). Le cadre précis des titres requis et suffisants fera l'objet de <strong>dispositions complémentaires</strong> ultérieures.",
    "source": "APD S1 – Art. 1 (modification ECA) / Référentiel ECA / FAQ FWB – ECA",
    "alerte": "Dans l'attente des textes définitifs sur les titres, les directions doivent veiller à ce que chaque élève bénéficie des trois modes d'expression chaque année, en combinant, le cas échéant, plusieurs professeurs en ECA. Lorsque les périodes sont regroupées (par exemple 2 périodes toutes les deux semaines), la coordination entre enseignants est essentielle pour garantir la cohérence des apprentissages et la couverture intégrale du référentiel.",
    "visible": true
  }
];
